#!/usr/bin/env bash

# Bar
BAR_POSITION="top"
BAR_MARGIN=0
BAR_Y_OFFSET=0
BAR_CORNER_RADIUS=0
BAR_HEIGHT=34
BAR_COLOR="0x00000000"
BAR_TOPMOST="window"

# Defaults
ITEM_PADDING_LEFT=8
ITEM_PADDING_RIGHT=8
ICON_FONT="JetBrainsMono Nerd Font:Bold:14.0"
# LABEL_FONT="Barlow:Normal:14.0"
LABEL_FONT="JetBrainsMono Nerd Font:Bold:14.0"
ITEM_BACKGROUND_DRAWING="off"
ICON_PADDING_RIGHT=6

# Colors
ACCENT_COLOR="0xfff2fcff"
TEXT_COLOR="0xffd6e2ee"

# Items
SPACE_COUNT=6
CLOCK_ICON="󰥔"
BATTERY_ICON="󰁹"
RAM_ICON="󰍛"
CPU_ICON="󰘚"
CLOCK_UPDATE_FREQ=10
BATTERY_UPDATE_FREQ=120
RAM_UPDATE_FREQ=10
CPU_UPDATE_FREQ=10
